version: '3'
services:
  app:
    build: .
    container_name: temp-hist-challenge
    depends_on:
      - redis
    networks:
      - redis-net
  redis:
    image: "redis"
    container_name: redis
    volumes:
      - ./data:/data
    entrypoint: redis-server --appendonly yes
    restart: always
    ports:
      - "6379:6379"
    networks:
      - redis-net

networks:
  redis-net: